name: Tech Memes (Every 4 Hours)

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  meme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Run meme script
        env:
          MEMES_DISCORD: ${{ secrets.MEMES_DISCORD }}
        run: |
          chmod +x pennywise.sh
          ./pennywise.sh